import '@radix-ui/themes/styles.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Container, Theme } from '@radix-ui/themes'
import './globals.css'
import NavBar from './NavBar'
import AuthProvider from './auth/Provider'
import QueryClientProvider from './QueryClientProvider'

const avenir = localFont({
	src: '../public/fonts/Avenir-Black.woff2',
	variable: '--font-avenir',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${avenir.variable} antialiased`}>
				<QueryClientProvider>
					<AuthProvider>
						<Theme appearance="dark" accentColor="tomato">
							<NavBar />
							<main className="p-5">
								<Container>{children}</Container>
							</main>
						</Theme>
					</AuthProvider>
				</QueryClientProvider>
			</body>
		</html>
	)
}
